Manager/Manager/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'Manager.views.home', name='home'),
    url(r'^about$', 'Manager.views.about', name='about'),
    url(r'^admins$', 'Manager.views.admin', name='admin'),
    url(r'^na$', 'Manager.views.not_available', name='N/A'),
    url(r'^ff$', 'Manager.views.navigator', name='Navigator'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^movies/', include('movies.urls', namespace='movies')),
    url(r'^tv/', include('tvseries.urls', namespace='tvseries')),
    url(r'^toons/', include('toons.urls', namespace='toons')),

    url(r'^admin/', include(admin.site.urls)),

)

Manager/movies/urls.py
from django.conf.urls import patterns, url

from movies import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^settings/$', views.settings, name='settings'),
)

Manager/toons/urls.py
from django.conf.urls import patterns, url

from toons import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^settings/$', views.settings, name='settings'),
)

Manager/tvseries/urls.py
from django.conf.urls import patterns, url

from tvseries import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^settings/$', views.settings, name='settings'),
)

Manager/Manager/models.py
from django.db import models


class LibraryPath(models.Model):
    """Defines the db for storing HDD paths for importing Media Collection"""
    path = models.CharField(max_length=500)
    type = models.CharField(max_length=100)

    '''
    def __init__(self, path, type):
        self.path = path
        self.type = type
    '''
    class Meta:
        unique_together = ['type', 'path']

    def __str__(self):
        return self.type + " : " + self.path

Manager/movies/models.py
from django.db import models

# Create your models here.
#once the db table is created from the model, it cant be recreated...so updates cant be synced with syncdb
class Movie(models.Model):

    title = models.CharField(max_length=200)

    #from directory or imdb?
    year = models.CharField(max_length=10,blank=True)
    #other info from imdb here
    genre = models.CharField(max_length=200,blank=True)
    type = models.CharField(max_length=200,blank=True)
    duration = models.CharField(max_length=200,blank=True)
    category = models.CharField(max_length=200,blank=True)
    plot = models.TextField(blank=True)
    tagline = models.TextField(null=True,blank=True)
    rating = models.CharField(max_length=200,blank=True)
    #some db values will not be shown even in admin form
    poster = models.TextField(max_length=200,blank=True)
    cast = models.TextField(max_length=600,blank=True)
    directors = models.TextField(max_length=200,blank=True)
    #present or not....once seen its stored in db
    present = models.BooleanField()

    def __str__(self):
        return self.title

Manager/toons/models.py
from django.db import models

# Create your models here.

Manager/tvseries/models.py
from django.db import models

# Create your models here.

Manager/Manager/forms.py
from django import forms
from Manager.models import LibraryPath

class LibraryPathForm(forms.ModelForm):
    class Meta(object):
        model = LibraryPath
        fields = ['type', 'path']

Manager/Manager/views.py
from django.shortcuts import render
#from django.http import HttpResponse


def home(request, **kwargs):
    return render(request, 'manager/index.html')
    #return HttpResponse("<h1>Working!</h1>")


def about(request, **kwargs):
    return render(request, 'manager/about.html')


def admin(request, **kwargs):
    return render(request, 'manager/admin.html')


def not_available(request, **kwargs):
    return render(request, 'manager/unavailable.html')


def navigator(request, **kwargs):

    import os
    import psutil
    from Manager.forms import LibraryPathForm
    from django.contrib import messages

    destination = ''
    dirs = []
    files = []

    if request.method == 'POST':
        # create a form instance and populate it with data from the request
        form = LibraryPathForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.INFO, 'Successfully added the path. It would be used for importing media into Collection.')
        else:
            messages.add_message(request, messages.INFO, 'Could not add the path. Already exists.')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = LibraryPathForm()

    drives = [each.mountpoint for each in psutil.disk_partitions() if 'fixed' in each.opts]

    if request.GET.get('dir'):
        destination = request.GET.get('dir')
        try:
            os.chdir(destination)
        except Exception as e:
            messages.add_message(request, messages.WARNING, "Access Denied")

        dirs = [each for each in os.listdir(os.getcwd()) if os.path.isdir(each)]
        files = [each for each in os.listdir(os.getcwd()) if os.path.isfile(each)]
        current = os.getcwd()
    else:
        current = 'Computer Root'

    context = {'parent': destination, 'current': current, 'drives': drives, 'dirs': dirs, 'files': files, 'form': form}

    return render(request, 'manager/ff.html', context)

Manager/movies/views.py
from django.shortcuts import render


# Create your views here.
def index(request, **kwargs):
    return render(request, 'movies/index.html')


def settings(request, **kwargs):

    from Manager.models import LibraryPath
    from movies.models import Movie

    if request.GET.get('path'):
        path_to_delete = LibraryPath.objects.filter(path=request.GET.get('path'), type='movies')
        for each in path_to_delete:
            each.delete()

    paths = LibraryPath.objects.filter(type='movies')
    movies = Movie.objects.all()

    context = {'paths': paths, 'media_list': movies, 'item': 'Movies', 'app':'movies'}

    return render(request, 'movies/settings.html', context)

Manager/toons/views.py
from django.shortcuts import render


# Create your views here.
def index(request, **kwargs):
    return render(request, 'toons/index.html')


def settings(request, **kwargs):

    from Manager.models import LibraryPath
    #from movies.models import Movie

    if request.GET.get('path'):
        path_to_delete = LibraryPath.objects.filter(path=request.GET.get('path'), type='toons')
        for each in path_to_delete:
            each.delete()

    paths = LibraryPath.objects.filter(type='toons')
    #movies = Movie.objects.all()
    toons = []

    context = {'paths': paths, 'media_list': toons, 'item': 'Toons', 'app':'toons'}

    return render(request, 'toons/settings.html', context)

Manager/tvseries/views.py
from django.shortcuts import render

# Create your views here.
def index(request, **kwargs):
    return render(request, 'tvseries/index.html')


def settings(request, **kwargs):

    from Manager.models import LibraryPath
    #from movies.models import Movie

    if request.GET.get('path'):
        path_to_delete = LibraryPath.objects.filter(path=request.GET.get('path'), type='tvseries')
        for each in path_to_delete:
            each.delete()

    paths = LibraryPath.objects.filter(type='tvseries')
    #movies = Movie.objects.all()
    shows = []

    context = {'paths': paths, 'media_list': shows, 'item': 'TV Series', 'app':'tvseries'}

    return render(request, 'tvseries/settings.html', context)

Manager/movies/templates/movies/index.html
{% extends 'manager/base.html' %}

{% block title%}- Movies{% endblock %}

{% block content %}
    <div class="jumbotron"></div>
{% endblock content %}

Manager/movies/templates/movies/settings.html
{% extends 'manager/settings.html' %}

Manager/templates/manager/about.html
{% extends 'manager/base.html' %}

{% block title%}- About{% endblock %}

{% block content %}
    <div class="jumbotron">
        <h1>About the software</h1>
        <blockquote>
            <p>Created by HZ.</p>
            <p>The following features are added.</p>
            <ul>
                <li>Cataloguing and organizing Movies, TV Shows, Cartoon Series in collection</li>
                <li>Give the path to the root of Movies/TV shows/Cartoons and it automatically acquires the proper info</li>
                <li>Ability to manually add or modify the info.</li>
                <li>Keeps record of entries not obtained automatically.</li>
            </ul>
        </blockquote>

    </div>
{% endblock content %}

Manager/templates/manager/admin.html
{% extends 'manager/base.html' %}

{% block title%}- Admin{% endblock %}

{% block content %}
    <div class="jumbotron">
        <iframe src="/admin/" width="100%" height="500"></iframe>
    </div>
{% endblock content %}

Manager/templates/manager/base.html
<!DOCTYPE html>

<html>
	<head>
		<title>Collection {% block title %}{% endblock %}</title>

        <!--Add BootStrap-->
        <meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		{% load staticfiles %}

        {% block css %}
        <!-- Latest compiled and minified CSS JS -->
        <link rel="stylesheet" type="text/css" href="{% static 'manager/bootstrap-3.3.2/css/bootstrap.min.css' %}" />
{#        <link rel="stylesheet" type="text/css" href="{% static 'manager/typicon/font/typicons.min.css' %}" />#}
        <link rel="stylesheet" type="text/css" href="{% static 'manager/font-awesome/css/font-awesome.min.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'manager/mystyles.css' %}"/>
        {% endblock css %}

        {% block js %}
        <script src="{% static 'manager/jquery.min.js' %}"></script>
        <script src="{% static 'manager/bootstrap-3.3.2/js/bootstrap.min.js' %}"></script>
        {% endblock js %}
	</head>
	
	<body>

        <div id="container" class="container-fluid">
            <div class="rect1"></div>
            <!-- Static header navbar -->
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'Manager.views.home' %}">HZ's Collection Organizer</a>
                    </div>

                    <div id="navbar" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li><a href="{% url 'Manager.views.home' %}"><button type="button" class="btn btn-lg btn-success"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home</button></a></li>

                            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><button type="button" class="btn btn-lg btn-info"><span class="glyphicon glyphicon-gift" aria-hidden="true"></span> Collection <span class="caret"></span></button></a>

                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'movies:index' %}"><span class="glyphicon glyphicon-film" aria-hidden="true"></span> Movies</a></li>
                                    <li><a href="{% url 'tvseries:index' %}"><img src="{% static 'manager/tv.png' %}"/> TV Series</a></li>
                                    <li><a href="{% url 'toons:index' %}"><img src="{% static 'manager/tf.png' %}"/> Cartoons</a></li>
                                    <li class="divider"></li>
                                    <li class="dropdown-header">Others</li>
                                    <li><a href="{% url 'Manager.views.not_available' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span> Music</a></li>
                                    <li><a href="{% url 'Manager.views.not_available' %}"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> Books</a></li>
                                </ul>
                            </li>
                            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><button type="button" class="btn btn-lg btn-warning"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Settings <span class="caret"></span></button></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'Manager.views.navigator' %}"><span
                                            class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Add Library Path</a></li>
                                    <li class="divider"></li>
                                    <li class="dropdown-header">Edit</li>
                                    <li><a href="{% url 'movies:settings' %}"><span class="glyphicon glyphicon-film" aria-hidden="true"></span> Movies</a></li>
                                    <li><a href="{% url 'tvseries:settings' %}"><img src="{% static 'manager/tv.png' %}"/> TV Series</a></li>
                                    <li><a href="{% url 'toons:settings' %}"><img src="{% static 'manager/tf.png' %}"/> Cartoons</a></li>
                                    <li class="divider"></li>
                                    <li class="dropdown-header">Others</li>
                                    <li><a href="{% url 'Manager.views.not_available' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span> Music</a></li>
                                    <li><a href="{% url 'Manager.views.not_available' %}"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> Books</a></li>
                                    <li class="divider"></li>
                                    <li class="dropdown-header">Admin Panel</li>
                                    <li><a href="{% url 'Manager.views.admin' %}"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span> Administration</a></li>
                                </ul>
                            </li>

                            <li><a href="{% url 'Manager.views.about' %}"><button type="button" class="btn btn-lg btn-danger"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> About</button></a></li>

                        </ul>

                    </div><!--/.nav-collapse -->
                </div><!--/.container-fluid -->
            </nav>

            <!-- Content -->
            {% block content %}

            {% endblock content %}
            <!-- content end -->

            <!-- footer -->
            <div class="row">
                <div class="col-lg-1 col-md-2 col-sm-2 col-xs-4">&copy 2014 HZ</div>
                <div class="col-lg-2 col-md-2 col-sm-3 col-xs-6">Powered by django</div>
                <div class="col-lg-9 col-md-8 col-sm-7 col-xs-2">Help</div>
            </div>
            <!-- footer end -->
        </div>
	</body>
</html>

Manager/templates/manager/ff.html
{% extends 'manager/base.html' %}

{% block title%}- Add Library{% endblock %}

{% block content %}
    <form action="{% url 'Manager.views.navigator' %}" method="post" class="form-inline">
        {% csrf_token %}
        <fieldset>
            <legend>Add path</legend>
            <label>Path:&nbsp;&nbsp;</label><label class="panel popover-title">{{ current }}</label>
            <input name="path" value="{{ current }}" type="hidden"/>
            <br/>
            <br/>
            <label>Media Type: </label>
            <select name="type" class="form-control">
                <option value="movies">Movies</option>
                <option value="tvseries">TV Series</option>
                <option value="toons">Cartoons</option>
            </select>
            <br/>
            <br/>
            <input type="submit" value="Add" class="form-control btn-danger"/>
        </fieldset>
    </form>
    <br/>

    {% if messages %}
    <div class="">
        <ul class="list-group">
        {% for message in messages %}
            {% if message.tags == 'info' %}
                <li class="list-group list-group-item list-group-item-heading list-group-item-warning"><b><span class="glyphicon glyphicon-flash"></span> {{ message }}</b></li>
            {% endif %}
        {% endfor %}
        </ul>
    </div>
    {% endif %}


    <div class="jumbotron">
        <p class="panel popover-title text-center"><span class="glyphicon glyphicon glyphicon-search"></span> Directory Explorer</p>
        {% if request.GET.dir %}
            {% if current in drives %}
                <a href="{% url 'Manager.views.navigator' %}"><h2 class="fa fa-arrow-circle-left"> Back</h2></a>
            {% else %}
                <a href="{% url 'Manager.views.navigator' %}?dir=.."><h2 class="fa fa-arrow-circle-left"> Back</h2></a>
            {% endif %}
            <span>&NonBreakingSpace;&NonBreakingSpace;&NonBreakingSpace;&NonBreakingSpace;&NonBreakingSpace;&NonBreakingSpace;</span>
            <a href="{% url 'Manager.views.navigator' %}"><h2 class="fa fa-desktop"> Computer</h2></a>
        {% else %}
            <h2 class="fa fa-desktop"> Computer</h2>
        {% endif %}
        <div class="row">
            <p class="col-lg-2 col-md-2 col-sm-2 text-right address">Address</p>
            <p class="panel modal-title col-lg-10 col-md-10 col-sm-10 col-xs-12">{{ current }}</p>
        </div>
        <hr/>
        {% if not dirs and not files and not parent %}
            {% for each in drives %}
                <a href="{% url 'Manager.views.navigator' %}?dir={{ each|urlencode }}"><p class="glyphicon glyphicon-hdd"> {{ each }}</p>
                </a><br/>
            {% endfor %}
            <hr/>
        {% endif %}

        {% if messages %}
            <div class="">
                <ul class="list-group">
                    {% for message in messages %}
                        {% if message.tags == 'warning' %}
                            <li class="list-group list-group-item list-group-item-heading list-group-item-warning">
                                <b><span class="glyphicon glyphicon-flash"></span> {{ message }}</b></li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        {% if dirs %}
            <p><b><i>Folders</i></b></p>

        {% for each in dirs %}
            <a href="{% url 'Manager.views.navigator' %}?dir={{ each|urlencode }}"><p class="glyphicon glyphicon-folder-open"> {{ each }}</p></a><br/>
        {% endfor %}
            <hr/>
        {% endif %}

        {% if files %}
            <p><b><i>Files</i></b></p>
        {% for each in files %}
            <span class="glyphicon glyphicon-file"> {{ each }}</span><br/>
        {% endfor %}
            <hr/>
        {% endif %}
    </div>
{% endblock content %}

Manager/templates/manager/index.html
{% extends 'manager/base.html' %}

{% block title%}- Main page{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1>HZ's Collection Organizer</h1>
    <blockquote>
        <p>A tool for organizing digital collection of media, e.g. Movies, TV shows, Cartoon Series. Also Music, Books and other types of Collectables are kept in todo list.</p>
    </blockquote>
    <p>
        <a class="btn btn-lg btn-primary" href="{% url 'Manager.views.about' %}" role="button">View Software Features &raquo;</a>
    </p>
</div>
{% endblock content %}

Manager/templates/manager/settings.html
{% extends 'manager/base.html' %}

{% block title %}- {{ item }} Settings{% endblock %}

{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'manager/DataTables/css/jquery.dataTables.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'manager/DataTables/css/dataTables.tableTools.css' %}"/>
{% endblock css %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'manager/DataTables/js/jquery.dataTables.js' %}"></script>
    <script type="text/javascript" src="{% static 'manager/DataTables/js/dataTables.tableTools.js' %}"></script>
{% endblock js %}

{% block content %}
    <div class="jumbotron">
        <h3 class="breadcrumb modal-header text-center"><span class="glyphicon glyphicon-th-list"> {{ item }} Drives</span></h3>
        {% if paths %}
            <table id="paths_table">
            <caption>Paths Table</caption>
                <thead>
                    <tr>
                        <th>Paths</th>
                    </tr>
                </thead>
                <tbody>
                {% for each in paths %}
                    <tr><td>{{ each.path }}</td></tr>
                {% endfor %}
                </tbody>
                <tfoot><tr><td>Total Paths: {{ paths|length }}</td></tr></tfoot>
            </table>
            <button id="btn">Delete</button>
        {% else %}
            <p class="popover-content text-warning"><span class="glyphicon glyphicon-warning-sign"> No path added to {{ item }} Collections</span></p>
        {% endif %}

        <h2 class="breadcrumb modal-header text-center"><span class="glyphicon glyphicon-paperclip"> {{ item }} Collection</span></h2>
        {% if media_list %}
        {% else %}
            <p class="popover-content text-warning"><span class="glyphicon glyphicon-warning-sign"> No {{ item }} Collection added</span>
            </p>
        {% endif %}
    </div>

    <script type="text/javascript">
        $(document).ready(function(){
            var $table = '#paths_table';
            var dt_opts = {
                "sPaginationType": "full_numbers",
                "lengthMenu": [ 5,10,15,20 ],
                dom: 'T<"clear">lfrtip',
                tableTools: {
                    "sRowSelect": "os",
                    "aButtons": [
                        //"copy"
                        //"print",
                        //{
                            //"sExtends":    "collection",
                            //"sButtonText": "Save",
                            //"aButtons":    [ "csv", "xls", "pdf" ]
                        //}
                    ]
                }
            };
            $($table).DataTable(dt_opts);
{#            $(table + ' tbody tr' ).click(function () {#}
{#                if ( $(this).hasClass('selected') ) {#}
{#                    $(this).removeClass('selected');#}
{#                }#}
{#                else {#}
{#                    $(table + ' tbody tr.selected').removeClass('selected');#}
{#                    $(this).addClass('selected');#}
{#                }#}
{#            });#}
            $('#btn').click( function () {
                //alert($table.row('.selected'));
                $($table + ' tr.selected').remove().draw();
            } );
        });
    </script>
{% endblock content %}

Manager/templates/manager/unavailable.html
{% extends 'manager/base.html' %}

{% block title%}- Not Available{% endblock %}

{% block content %}
    <div class="jumbotron">
        <strong>This portion is not implemented yet.</strong>
    </div>
{% endblock content %}

Manager/toons/templates/toons/index.html
{% extends 'manager/base.html' %}

{% block title%}- Cartoons{% endblock %}

{% block content %}
    <div class="jumbotron"></div>
{% endblock content %}

Manager/toons/templates/toons/settings.html
{% extends 'manager/settings.html' %}

Manager/tvseries/templates/tvseries/index.html
{% extends 'manager/base.html' %}

{% block title%}- TV Shows{% endblock %}

{% block content %}
    <div class="jumbotron"></div>
{% endblock content %}

Manager/tvseries/templates/tvseries/settings.html
{% extends 'manager/settings.html' %}